# Generated by Django 4.1.7 on 2023-04-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Sandy',
        ),
    ]
